In [1]:
import numpy as np
import scipy.sparse as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
from astropy.io import fits
from astropy.stats import sigma_clip
from astropy.coordinates import SkyCoord
import astropy.units as u
from astropy.visualization import simple_norm
from astropy.wcs import WCS
from spectral_cube import SpectralCube as sc
from sklearn.cluster import DBSCAN
from tqdm.notebook import trange
import os
import warnings
from copy import deepcopy

np.seterr(divide="ignore", invalid="ignore")
np.set_printoptions(precision=10, suppress=True)
eps = 1e-12

#%matplotlib ipympl

In [ ]:
a = np.array([[[1, 2], [3, 4]], [[101, 102], [103, 104]]])
b = np.array([[[5, 6], [7, 8]], [[105, 106], [107, 108]]])
c = np.array([[[17, 18], [19, 20]], [[117, 118], [119, 120]]])
d = np.array([[[21, 22], [23, 24]], [[121, 122], [123, 124]]])
row1 = np.concatenate((a, b), axis=1)
row2 = np.concatenate((c, d), axis=1)
full = np.concatenate((row1, row2), axis=2)

# [[[  1   2  17  18]
#   [  3   4  19  20]
#   [  5   6  21  22]
#   [  7   8  23  24]]
#
#  [[101 102 117 118]
#   [103 104 119 120]
#   [105 106 121 122]
#   [107 108 123 124]]]

In [2]:
file_E12 = "./HI4PI/CAR_E12.fits"
hdul_E12 = fits.open(file_E12)
hdr_E12 = hdul_E12[0].header
wcs_E12 = WCS(hdr_E12)
wcsc_E12 = wcs_E12.celestial
data_nan_E12 = hdul_E12[0].data.astype(np.float64)
data_nan_E12 = data_nan_E12[:,:240,:]

In [3]:
file_F12 = "./HI4PI/CAR_F12.fits"
hdul_F12 = fits.open(file_F12)
hdr_F12 = hdul_F12[0].header
wcs_F12 = WCS(hdr_F12)
wcsc_F12 = wcs_F12.celestial
data_nan_F12 = hdul_F12[0].data.astype(np.float64)

In [4]:
data_merge = np.concatenate((data_nan_E12, data_nan_F12), axis=1)
data_0 = data_merge[568,:,:]

In [5]:
hdu_merge = fits.PrimaryHDU(data=data_merge, header=hdr_E12)
hdu_merge.writeto('./HI4PI/HI4PI_E12_F12_merge.fits', overwrite=True)